# Generated by Django 4.1 on 2022-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teampage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Adınız')),
                ('image', models.ImageField(blank=True, help_text='420x424 boyutunda resim önerilmektedir.', null=True, upload_to='media/images/site/team/', verbose_name='Takım Arkadaşının Resmi')),
                ('description', models.CharField(max_length=200, verbose_name='Görevi')),
            ],
        ),
    ]
