# Generated by Django 4.1 on 2022-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teampage',
            options={'ordering': ('order',), 'verbose_name': 'team', 'verbose_name_plural': 'team'},
        ),
        migrations.AddField(
            model_name='teampage',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Sıra'),
        ),
    ]
