# Generated by Django 4.1 on 2022-10-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_teampage_options_teampage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='status',
            field=models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], default=1, max_length=100, verbose_name='Gallery Statüsü'),
            preserve_default=False,
        ),
    ]
