# Generated by Django 4.1 on 2022-10-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teampage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Adınız')),
                ('image', models.ImageField(blank=True, help_text='420x424 boyutunda resim önerilmektedir.', null=True, upload_to='media/images/site/team/', verbose_name='Takım Arkadaşının Resmi')),
                ('description', models.CharField(max_length=200, verbose_name='Görevi')),
                ('url_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sponsor Url Adı')),
                ('url_adres', models.URLField(blank=True, null=True, verbose_name='Sponsor Url adresi')),
                ('order', models.IntegerField(default=1, verbose_name='Sıra')),
                ('status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Gallery Statüsü')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsor',
                'ordering': ('order',),
            },
        ),
    ]
