# Generated by Django 4.1 on 2022-10-13 17:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sponsorpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorpage',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Görevi'),
        ),
        migrations.AlterField(
            model_name='sponsorpage',
            name='image',
            field=models.ImageField(blank=True, help_text='420x424 boyutunda resim önerilmektedir.', null=True, upload_to='media/images/site/sponsor/', verbose_name='Sponsor Resmi'),
        ),
    ]
