# Generated by Django 4.1 on 2022-10-13 17:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_sponsorpage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blogs')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('order', models.IntegerField(default=1, verbose_name='Sıra')),
                ('status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Statüsü')),
            ],
            options={
                'verbose_name': 'Projeler',
                'verbose_name_plural': 'Projeler',
                'ordering': ('order',),
            },
        ),
    ]
