# Generated by Django 4.1 on 2022-10-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_projectpage_içerik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
