# Generated by Django 4.1 on 2022-10-16 19:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_projectpage_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('içerik', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.IntegerField(default=1, verbose_name='Sıra')),
                ('status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Statüsü')),
            ],
            options={
                'verbose_name': 'Projeler',
                'verbose_name_plural': 'Projeler',
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='image',
            field=models.ImageField(upload_to='media/images/site/project/'),
        ),
    ]
