# Generated by Django 4.1 on 2022-10-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_page_options_remove_page_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Sayfalar', 'verbose_name_plural': 'Sayfalar'},
        ),
    ]
