# Generated by Django 4.1 on 2022-10-21 17:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='içerik',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
