# Generated by Django 4.1 on 2022-09-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=256, verbose_name='site adı')),
                ('siteslogan', models.CharField(max_length=256, verbose_name='site sloganı')),
                ('site_favicon', models.ImageField(height_field=16, upload_to='images/site/favicon/', verbose_name='favicon', width_field=16)),
            ],
        ),
    ]
