# Generated by Django 4.1 on 2022-09-05 16:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email adresi'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='telefon numarası'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_favicon',
            field=models.ImageField(upload_to='media/images/site/favicon/', verbose_name='favicon'),
        ),
    ]
