# Generated by Django 4.1 on 2022-10-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_site_site_email_site_site_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Sıra'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_adres',
            field=models.CharField(default=1, max_length=400, verbose_name='Okul Adresi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='site_adres_url',
            field=models.URLField(default=1, verbose_name='Okul Adresi'),
            preserve_default=False,
        ),
    ]
