# Generated by Django 4.1 on 2022-10-03 19:13

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_site_order_site_site_adres_site_site_adres_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='site',
            name='site_adres',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Okul Adresi'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_adres_url',
            field=models.URLField(blank=True, null=True, verbose_name='Okul Adresi Url'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='telefon numarası'),
        ),
    ]
