# Generated by Django 4.1 on 2022-10-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_alter_site_options_alter_site_site_adres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook Url'),
        ),
        migrations.AddField(
            model_name='site',
            name='instgram_url',
            field=models.URLField(blank=True, null=True, verbose_name='instgram adresi'),
        ),
        migrations.AddField(
            model_name='site',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='twitter Url'),
        ),
    ]
