# Generated by Django 4.1 on 2022-10-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_site_facebook_url_site_instgram_url_site_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='copyright',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='copyright'),
        ),
    ]
