# Generated by Django 4.1 on 2022-10-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_site_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_logo',
            field=models.ImageField(default=1, upload_to='media/images/site/logo/', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
