# Generated by Django 4.1 on 2022-09-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='menü adı')),
                ('menu_url', models.URLField(max_length=300, verbose_name='menü url')),
                ('menu_status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='menü statüsü')),
                ('ust_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appearance.menu', verbose_name='üst kategori')),
            ],
        ),
    ]
