# Generated by Django 4.1 on 2022-09-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.SlugField(max_length=300, verbose_name='menü url'),
        ),
    ]
