# Generated by Django 4.1 on 2022-09-05 17:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_alter_menu_ust_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='menü adı'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ust_menu',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appearance.menu', verbose_name='üst kategori'),
        ),
    ]
