# Generated by Django 4.1 on 2022-09-05 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_alter_menu_menu_name_alter_menu_ust_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ust_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appearance.menu', verbose_name='üst kategori'),
        ),
    ]
