# Generated by Django 4.1 on 2022-09-05 17:36

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_menus_delete_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='ust_menu',
            field=mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appearance.menus', verbose_name='üst kategori'),
        ),
    ]
