# Generated by Django 4.1 on 2022-09-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0008_alter_menus_ust_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menus',
        ),
    ]
