# Generated by Django 4.1 on 2022-09-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu',
        ),
    ]
