# Generated by Django 4.1 on 2022-09-05 18:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appearance', '0011_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('menu_name', models.CharField(max_length=100, verbose_name='menü adı')),
                ('menu_url', models.SlugField(max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='menü url')),
                ('menu_status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='menü statüsü')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('ust_menu', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='appearance.menu', verbose_name='üst kategori')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
