# Generated by Django 4.1 on 2022-09-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.URLField(max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='menü url'),
        ),
    ]
