# Generated by Django 4.1 on 2022-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0013_alter_menu_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.SlugField(blank=True, max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='menü url'),
        ),
    ]
