# Generated by Django 4.1 on 2022-09-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0014_alter_menu_menu_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('slider_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('slider_image', models.ImageField(upload_to='media/images/site/slider', verbose_name='slider resmi')),
                ('slider_title', models.CharField(max_length=100)),
                ('slider_description', models.TextField()),
                ('slider_button_title', models.CharField(max_length=50)),
                ('slider_button_url', models.SlugField()),
                ('slider_order', models.IntegerField(editable=False)),
            ],
        ),
    ]
