# Generated by Django 4.1 on 2022-09-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0015_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('slider_order',)},
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_order',
            field=models.IntegerField(),
        ),
    ]
