# Generated by Django 4.1 on 2022-09-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0016_alter_slider_options_alter_slider_slider_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_status',
            field=models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], default='Published', max_length=100, verbose_name='Slider Statüsü'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_order',
            field=models.IntegerField(default=1, verbose_name='sıra'),
        ),
    ]
