# Generated by Django 4.1 on 2022-09-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0017_slider_slider_status_alter_slider_slider_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_activate',
            field=models.BooleanField(default=False, verbose_name='menü çizgisi'),
        ),
    ]
