# Generated by Django 4.1 on 2022-09-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0018_menu_menu_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('icon_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('icon_image', models.ImageField(upload_to='media/images/site/icons/', verbose_name='icon image')),
                ('icon_image_url', models.URLField(verbose_name='icon resim url adresi')),
            ],
        ),
    ]
