# Generated by Django 4.1 on 2022-09-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0019_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/site/icons/', verbose_name='icon image'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='icon resim url adresi'),
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('feature_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('feature_image', models.ImageField(upload_to='media/images/site/icons/', verbose_name='resim')),
                ('feature_first_title', models.CharField(max_length=100)),
                ('feature_first_button_title', models.CharField(max_length=100)),
                ('feature_first_button_url', models.SlugField(verbose_name='birinci url')),
                ('feature_second_title', models.CharField(max_length=100)),
                ('feature_second_url', models.SlugField(verbose_name='İkinci url')),
                ('feature_second_description', models.TextField(verbose_name='ikinci bölüm açıklama')),
                ('feature_third_title', models.CharField(max_length=100)),
                ('feature_third_url', models.SlugField(verbose_name='üçüncü url')),
                ('feature_third_description', models.TextField(verbose_name='üçüncü bölüm açıklama')),
                ('feature_fourth_title', models.CharField(max_length=100)),
                ('feature_fourth_url', models.SlugField(verbose_name='dördüncü url')),
                ('feature_fourth_description', models.TextField(verbose_name='dördüncü bölüm açıklama')),
                ('feature_fourth_icons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_fourth_icons', to='appearance.icon', verbose_name='dördüncü icon')),
                ('feature_second_icons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_second_icons', to='appearance.icon', verbose_name='ikinci icon')),
                ('feature_third_icons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_third_icons', to='appearance.icon', verbose_name='üçüncü icon')),
            ],
        ),
    ]
