# Generated by Django 4.1 on 2022-09-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0020_alter_icon_icon_image_alter_icon_icon_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_fourth_icons',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='feature_fourth_icons', to='appearance.icon', verbose_name='dördüncü icon'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_second_icons',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='feature_second_icons', to='appearance.icon', verbose_name='ikinci icon'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_third_icons',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='feature_third_icons', to='appearance.icon', verbose_name='üçüncü icon'),
        ),
    ]
