# Generated by Django 4.1 on 2022-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0021_alter_feature_feature_fourth_icons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'feature', 'verbose_name_plural': 'features'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(help_text='En uygun 415x592 boyutudur.', upload_to='media/images/site/icons/', verbose_name='resim'),
        ),
    ]
