# Generated by Django 4.1 on 2022-09-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0022_alter_feature_options_alter_feature_feature_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'feature', 'verbose_name_plural': 'feature'},
        ),
        migrations.AddField(
            model_name='feature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(max_length=100),
        ),
    ]
