# Generated by Django 4.1 on 2022-09-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0023_alter_feature_options_feature_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_order',
            field=models.IntegerField(default=1, verbose_name='sıra'),
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], default='Published', max_length=100),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_second_icons',
            field=models.ForeignKey(db_constraint=False, default='project', on_delete=django.db.models.deletion.PROTECT, related_name='feature_second_icons', to='appearance.icon', verbose_name='ikinci icon'),
        ),
    ]
