# Generated by Django 4.1 on 2022-09-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0024_feature_feature_order_feature_feature_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('feature_order',), 'verbose_name': 'feature', 'verbose_name_plural': 'feature'},
        ),
        migrations.AddField(
            model_name='icon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_fourth_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(help_text='En uygun 415x592 boyutudur.', upload_to='media/images/site/features/', verbose_name='resim'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_name',
            field=models.CharField(max_length=100),
        ),
    ]
