# Generated by Django 4.1 on 2022-09-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0025_alter_feature_options_icon_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_button_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_description_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_title_activate',
            field=models.BooleanField(default=True),
        ),
    ]
