# Generated by Django 4.1 on 2022-09-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0026_slider_slider_button_activate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('banner_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('banner_image', models.ImageField(upload_to='media/images/site/slider', verbose_name='slider resmi')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_title_activate', models.BooleanField(default=True)),
                ('banner_description', models.TextField()),
                ('banner_description_activate', models.BooleanField(default=True)),
                ('banner_button_title', models.CharField(max_length=50)),
                ('banner_button_url', models.SlugField()),
                ('banner_button_activate', models.BooleanField(default=True)),
                ('banner_button2_title', models.CharField(max_length=50)),
                ('banner_button2_url', models.SlugField()),
                ('banner_button2_activate', models.BooleanField(default=True)),
                ('banner_order', models.IntegerField(default=1, verbose_name='sıra')),
                ('banner_status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Slider Statüsü')),
            ],
            options={
                'ordering': ('banner_order',),
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('feature_order',), 'verbose_name': 'Feature', 'verbose_name_plural': 'Feature'},
        ),
    ]
