# Generated by Django 4.1 on 2022-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0028_alter_banner_banner_button2_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_gallery_name', models.CharField(max_length=200)),
                ('image_gallery_image', models.ImageField(help_text='1770x550 boyutunda resim önerilmektedir.', upload_to='media/images/site/banner', verbose_name='Banner resmi')),
            ],
        ),
        migrations.AddField(
            model_name='banner',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(max_length=200),
        ),
    ]
