# Generated by Django 4.1 on 2022-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0029_image_gallery_banner_id_alter_banner_banner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_for_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_for_information_name', models.CharField(max_length=200)),
                ('image_for_information_image', models.ImageField(help_text='1770x550 boyutunda resim önerilmektedir.', upload_to='media/images/site/image_gallery/', verbose_name='Banner resmi')),
            ],
        ),
        migrations.DeleteModel(
            name='image_gallery',
        ),
    ]
