# Generated by Django 4.1 on 2022-09-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0030_image_for_information_delete_image_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='information_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_gallery_name', models.CharField(help_text='admin sayfasında sizin göreceğiniz isim', max_length=200)),
                ('information_gallery_title', models.CharField(max_length=200)),
                ('information_gallery_description', models.CharField(max_length=400)),
                ('information_gallery_title_and_description_activate', models.BooleanField(default=True)),
                ('information_gallery_menu_name', models.CharField(max_length=200)),
                ('information_gallery_menu_activate', models.BooleanField(default=False)),
                ('information_gallery_order', models.IntegerField(default=1, verbose_name='Sıra')),
                ('information_gallery_status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='İnformation Gallery Statüsü')),
            ],
        ),
        migrations.AddField(
            model_name='image_for_information',
            name='image_for_information_description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image_for_information',
            name='image_for_information_title',
            field=models.CharField(default='selam', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image_for_information',
            name='image_for_information_title_url',
            field=models.SlugField(default="None", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_image',
            field=models.ImageField(help_text='420x350 boyutunda resim önerilmektedir.', upload_to='media/images/site/image_for_information/', verbose_name='gallery information resmi'),
        ),
    ]
