# Generated by Django 4.1 on 2022-09-23 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0031_information_gallery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information_gallery',
            options={'ordering': ('information_gallery_order',)},
        ),
        migrations.AddField(
            model_name='information_gallery',
            name='information_gallery_image_inlines',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='appearance.image_for_information'),
            preserve_default=False,
        ),
    ]
