# Generated by Django 4.1 on 2022-09-24 20:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0033_remove_information_gallery_information_gallery_image_inlines_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information_gallery',
            options={'ordering': ('information_gallery_order',), 'verbose_name': 'Feature1', 'verbose_name_plural': 'İnformation'},
        ),
        migrations.AddField(
            model_name='image_for_information',
            name='a',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='appearance.image_for_information'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_button2_activate',
            field=models.BooleanField(default=True, verbose_name='Banner Buton Başlığı Aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_button2_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banner Buton Başlığı'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_button2_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Banner Buton Url Adresi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_button_activate',
            field=models.BooleanField(default=True, verbose_name='Banner Buton Başlığı Aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_button_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banner Buton Başlığı'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_button_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Banner Buton Url Adresi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_description',
            field=models.TextField(blank=True, null=True, verbose_name='Banner Açıklaması'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_description_activate',
            field=models.BooleanField(default=True, verbose_name='Banner Açıklaması Aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(max_length=200, verbose_name='Banner Adı'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banner Başlığı'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_title_activate',
            field=models.BooleanField(default=True, verbose_name='Banner Başlığı Aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_first_button_title',
            field=models.CharField(max_length=100, verbose_name='Buton Başlık'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_first_button_url',
            field=models.SlugField(verbose_name='Buton url'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_first_title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_fourth_description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_fourth_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_fourth_url',
            field=models.SlugField(verbose_name='Url Adresi'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(help_text='En uygun 415x592 boyutudur.', upload_to='media/images/site/features/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(max_length=100, verbose_name='Feature Adı'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_order',
            field=models.IntegerField(default=1, verbose_name='Sıra'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_second_description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_second_icons',
            field=models.ForeignKey(db_constraint=False, default='project', on_delete=django.db.models.deletion.PROTECT, related_name='feature_second_icons', to='appearance.icon', verbose_name='İcon Seç'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_second_title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_second_url',
            field=models.SlugField(verbose_name='Url Adresi'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_status',
            field=models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], default='Published', max_length=100, verbose_name='Feaure Statüsü'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_third_description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_third_icons',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='feature_third_icons', to='appearance.icon', verbose_name='İcon Seç'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_third_title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_third_url',
            field=models.SlugField(verbose_name='Url Adresi'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon_name',
            field=models.CharField(max_length=100, verbose_name='İcon Adı'),
        ),
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_description',
            field=ckeditor.fields.RichTextField(max_length=200, verbose_name='Resim Açıklaması'),
        ),
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_name',
            field=models.CharField(max_length=200, verbose_name='Resim Adı'),
        ),
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_title',
            field=models.CharField(max_length=200, verbose_name='Resim Başlığı'),
        ),
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_title_url',
            field=models.SlugField(max_length=500, verbose_name='Resim Başlığının Url Adresi'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_description',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Galeri Açıklaması'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_menu_activate',
            field=models.BooleanField(default=False, verbose_name='Galeri Menu aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_menu_name',
            field=models.CharField(max_length=200, verbose_name='Galeri Menü Adı'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_name',
            field=models.CharField(help_text='admin sayfasında sizin göreceğiniz isim', max_length=200, verbose_name='Galeri Adı'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_status',
            field=models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Gallery Statüsü'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_title',
            field=models.CharField(max_length=200, verbose_name='Galeri Başlığı'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_title_and_description_activate',
            field=models.BooleanField(default=True, verbose_name='Galeri Başlık Ve Açıklamanın aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_activate',
            field=models.BooleanField(default=False, verbose_name='Menü Çizgisi'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=100, verbose_name='Menü Adı'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_status',
            field=models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Menü Statüsü'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_url',
            field=models.SlugField(blank=True, max_length=300, primary_key=True, serialize=False, unique=True, verbose_name='Menü Url'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_button_activate',
            field=models.BooleanField(default=True, verbose_name='Slider Buton Aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_button_title',
            field=models.CharField(max_length=50, verbose_name='Slider Buton Başlık'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_button_url',
            field=models.SlugField(verbose_name='Slider Buton Url Adresi'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_description',
            field=models.TextField(verbose_name='Slider Açıklaması'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_description_activate',
            field=models.BooleanField(default=True, verbose_name='Slider Açıklaması Aktiflik Durumu'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Slider Adı'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title',
            field=models.CharField(max_length=100, verbose_name='Slider Başlık'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title_activate',
            field=models.BooleanField(default=True, verbose_name='Slider Adının Aktiflik Durumu'),
        ),
    ]
