# Generated by Django 4.1 on 2022-09-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0034_alter_information_gallery_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_for_information',
            old_name='a',
            new_name='image_for_information_foregeinkey',
        ),
    ]
