# Generated by Django 4.1 on 2022-09-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0035_rename_a_image_for_information_image_for_information_foregeinkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_for_information',
            options={'verbose_name': 'Resim', 'verbose_name_plural': 'Resim'},
        ),
        migrations.AlterModelOptions(
            name='information_gallery',
            options={'ordering': ('information_gallery_order',), 'verbose_name': 'Galeri Bilgisi', 'verbose_name_plural': 'Galeri Bilgisi'},
        ),
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_foregeinkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appearance.image_for_information', verbose_name='Resim Seçimi'),
        ),
    ]
