# Generated by Django 4.1 on 2022-09-25 10:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0036_alter_image_for_information_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_gallery',
            name='information_gallery_title',
            field=ckeditor.fields.RichTextField(help_text='admin sayfasında sizin göreceğiniz isim', max_length=200, verbose_name='Galeri Başlığı'),
        ),
    ]
