# Generated by Django 4.1 on 2022-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0037_alter_information_gallery_information_gallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_for_information',
            name='image_for_information_foregeinkey',
        ),
        migrations.AddField(
            model_name='image_for_information',
            name='image_for_information_foregeinkey',
            field=models.ManyToManyField(to='appearance.image_for_information', verbose_name='Resim Seçimi'),
        ),
    ]
