# Generated by Django 4.1 on 2022-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0039_alter_image_for_information_image_for_information_foregeinkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_foregeinkey',
            field=models.ManyToManyField(blank=True, to='appearance.image_for_information', verbose_name='Resim Seçimi'),
        ),
    ]
