# Generated by Django 4.1 on 2022-09-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0042_remove_information_gallery_image_for_information_foregeinkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_for_information',
            name='image_for_information_foregeinkey',
            field=models.ManyToManyField(to='appearance.image_for_information', verbose_name='Resim Seçimi'),
        ),
    ]
