# Generated by Django 4.1 on 2022-09-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0046_alter_information_gallery_image_for_information_foregeinkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_gallery',
            name='image_for_information_foregeinkey',
            field=models.ManyToManyField(to='appearance.information_gallery', verbose_name='Resim Seçimi'),
        ),
    ]
