# Generated by Django 4.1 on 2022-09-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0051_alter_information_gallery_image_for_information_foregeinkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_gallery',
            name='image_for_information_foregeinkey',
        ),
    ]
