# Generated by Django 4.1 on 2022-09-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0053_information_gallery_image_for_information_foregeinkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information_gallery',
            old_name='image_for_information_foregeinkey',
            new_name='foregeinkey',
        ),
    ]
