# Generated by Django 4.1 on 2022-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0055_alter_information_gallery_foregeinkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_gallery',
            name='foregeinkey',
            field=models.ManyToManyField(to='appearance.image_for_information', verbose_name='Resim Seçimi'),
        ),
    ]
