# Generated by Django 4.1 on 2022-09-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0056_alter_information_gallery_foregeinkey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information_gallery',
            options={'ordering': ('order',), 'verbose_name': 'Galeri Bilgisi', 'verbose_name_plural': 'Galeri Bilgisi'},
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_menu_activate',
            new_name='menu_activate',
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_menu_name',
            new_name='menu_name',
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='information_gallery',
            old_name='information_gallery_title_and_description_activate',
            new_name='title_and_description_activate',
        ),
    ]
