# Generated by Django 4.1 on 2022-09-27 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0057_alter_information_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_gallery',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100, null=True, verbose_name='Galeri Açıklaması'),
        ),
        migrations.AlterField(
            model_name='information_gallery',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, help_text='admin sayfasında sizin göreceğiniz isim', max_length=200, null=True, verbose_name='Galeri Başlığı'),
        ),
    ]
