# Generated by Django 4.1 on 2022-09-27 20:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0058_alter_information_gallery_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='admin sayfasında sizin göreceğiniz isim', max_length=200, verbose_name='Experience Adı')),
                ('effect_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200, verbose_name='Experience Başlığı')),
                ('description', ckeditor.fields.RichTextField(max_length=100, verbose_name='Açıklama')),
                ('button_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('button_url', models.SlugField(default=False, verbose_name='Buton Url')),
                ('first_information_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('first_information_number', models.PositiveSmallIntegerField()),
                ('first_information_symbol', models.CharField(blank=True, max_length=3, null=True)),
                ('first_information_description', models.CharField(blank=True, max_length=30, null=True)),
                ('second_information_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('second_information_number', models.PositiveSmallIntegerField()),
                ('second_information_symbol', models.CharField(blank=True, max_length=3, null=True)),
                ('second_information_description', models.CharField(blank=True, max_length=30, null=True)),
                ('third_information_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('third_information_number', models.PositiveSmallIntegerField()),
                ('third_information_symbol', models.CharField(blank=True, max_length=3, null=True)),
                ('third_information_description', models.CharField(blank=True, max_length=30, null=True)),
                ('fourth_information_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('fourth_information_number', models.PositiveSmallIntegerField()),
                ('fourth_information_symbol', models.CharField(blank=True, max_length=3, null=True)),
                ('fourth_information_description', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.IntegerField(default=1, verbose_name='Sıra')),
                ('status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Gallery Statüsü')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
    ]
