# Generated by Django 4.1 on 2022-09-30 16:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0059_experience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('order',), 'verbose_name': 'Experience', 'verbose_name_plural': 'Experience'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='button_url',
            field=models.SlugField(verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=300, verbose_name='Açıklama'),
        ),
    ]
