# Generated by Django 4.1 on 2022-09-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0060_alter_experience_options_alter_experience_button_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='first_information_symbol',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='fourth_information_symbol',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='second_information_symbol',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='third_information_symbol',
        ),
    ]
