# Generated by Django 4.1 on 2022-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0061_remove_experience_first_information_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='foregeinkey',
            field=models.ManyToManyField(to='appearance.experience', verbose_name='Resim Seçimi'),
        ),
    ]
