# Generated by Django 4.1 on 2022-09-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0063_alter_experience_foregeinkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='foregeinkey',
        ),
    ]
