# Generated by Django 4.1 on 2022-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0064_remove_experience_foregeinkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='foregeinkey',
            field=models.ManyToManyField(to='appearance.image_for_information', verbose_name='Resim Seçimi'),
        ),
    ]
