# Generated by Django 4.1 on 2022-09-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0065_experience_foregeinkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_more_with_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='admin sayfasında sizin göreceğiniz isim', max_length=200, verbose_name='Bilgi Adı')),
                ('title', models.CharField(max_length=200, verbose_name='Bilgi Başlığı')),
                ('first_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('first_description', models.CharField(blank=True, max_length=30, null=True)),
                ('first_button_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('first_button_url', models.SlugField(verbose_name='Buton Url')),
                ('first_button2_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('first_button2_url', models.SlugField(verbose_name='Buton Url')),
                ('second_information_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('second_information_description', models.CharField(blank=True, max_length=30, null=True)),
                ('second_button_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('second_button_url', models.SlugField(verbose_name='Buton Url')),
                ('second_button2_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('second_button2_url', models.SlugField(verbose_name='Buton Url')),
                ('third_information_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('third_information_number', models.PositiveSmallIntegerField()),
                ('third_information_description', models.CharField(blank=True, max_length=30, null=True)),
                ('third_button_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('third_button_url', models.SlugField(verbose_name='Buton Url')),
                ('third_button2_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('third_button2_url', models.SlugField(verbose_name='Buton Url')),
                ('fourth_information_name', models.CharField(max_length=200, verbose_name='Bilgi Adı')),
                ('fourth_information_description', models.CharField(blank=True, max_length=30, null=True)),
                ('fourth_button_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('fourth_button_url', models.SlugField(verbose_name='Buton Url')),
                ('fourth_button2_name', models.CharField(max_length=200, verbose_name='Buton Adı')),
                ('fourth_button2_url', models.SlugField(verbose_name='Buton Url')),
                ('order', models.IntegerField(default=1, verbose_name='Sıra')),
                ('status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Gallery Statüsü')),
                ('foreignkey', models.ManyToManyField(to='appearance.image_for_information', verbose_name='Resim Seçimi')),
            ],
            options={
                'verbose_name': 'Bilgi Bölümü',
                'verbose_name_plural': 'Bilgi Bölümü',
                'ordering': ('order',),
            },
        ),
    ]
