# Generated by Django 4.1 on 2022-10-01 17:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0066_get_more_with_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get_more_with_us',
            name='third_information_number',
        ),
        migrations.AddField(
            model_name='get_more_with_us',
            name='first_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Bilgi Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='get_more_with_us',
            name='fourth_information_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Bilgi Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='get_more_with_us',
            name='second_information_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Bilgi Başlık'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='get_more_with_us',
            name='third_information_title',
            field=models.CharField(default=1, max_length=200, verbose_name='Bilgi Başlık'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='first_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='fourth_information_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='second_information_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='third_information_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=30, null=True),
        ),
    ]
