# Generated by Django 4.1 on 2022-10-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0067_remove_get_more_with_us_third_information_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='second_information_description',
            new_name='second_description',
        ),
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='second_information_name',
            new_name='second_name',
        ),
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='second_information_title',
            new_name='second_title',
        ),
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='third_information_description',
            new_name='third_description',
        ),
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='third_information_name',
            new_name='third_name',
        ),
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='third_information_title',
            new_name='third_title',
        ),
    ]
