# Generated by Django 4.1 on 2022-10-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0068_rename_second_information_description_get_more_with_us_second_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='fourth_information_description',
            new_name='fourth_description',
        ),
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='fourth_information_name',
            new_name='fourth_name',
        ),
        migrations.RenameField(
            model_name='get_more_with_us',
            old_name='fourth_information_title',
            new_name='fourth_title',
        ),
    ]
