# Generated by Django 4.1 on 2022-10-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0069_rename_fourth_information_description_get_more_with_us_fourth_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get_more_with_us',
            name='foreignkey',
        ),
        migrations.AddField(
            model_name='get_more_with_us',
            name='image',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='image2', to='appearance.image_for_information', verbose_name='Resim 2'),
            preserve_default=False,
        ),
    ]
