# Generated by Django 4.1 on 2022-10-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0070_remove_get_more_with_us_foreignkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_more_with_us',
            name='image_2',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='image2', to='appearance.image_for_information', verbose_name='Resim 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='image',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='image1', to='appearance.image_for_information', verbose_name='Resim 1'),
        ),
    ]
