# Generated by Django 4.1 on 2022-10-02 19:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0071_get_more_with_us_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='get_more_with_us',
            options={'ordering': ('order',), 'verbose_name': 'Bilgi', 'verbose_name_plural': 'Bilgi'},
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='first_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='first_title',
            field=models.CharField(max_length=20, verbose_name='Bilgi Başlık'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='fourth_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='fourth_title',
            field=models.CharField(max_length=20, verbose_name='Bilgi Başlık'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='second_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='second_title',
            field=models.CharField(max_length=20, verbose_name='Bilgi Başlık'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='third_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='third_title',
            field=models.CharField(max_length=20, verbose_name='Bilgi Başlık'),
        ),
    ]
