# Generated by Django 4.1 on 2022-10-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0072_alter_get_more_with_us_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_more_with_us',
            name='first_button2_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='first_button2_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='first_button_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='first_button_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='fourth_button2_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='fourth_button2_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='fourth_button_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='fourth_button_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='second_button2_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='second_button2_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='second_button_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='second_button_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='third_button2_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='third_button2_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='third_button_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buton Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='third_button_url',
            field=models.SlugField(blank=True, null=True, verbose_name='Buton Url'),
        ),
    ]
