# Generated by Django 4.1 on 2022-10-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0073_alter_get_more_with_us_first_button2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_more_with_us',
            name='image_3',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='image3', to='appearance.image_for_information', verbose_name='Resim 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='get_more_with_us',
            name='image_4',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='image4', to='appearance.image_for_information', verbose_name='Resim 4'),
            preserve_default=False,
        ),
    ]
