# Generated by Django 4.1 on 2022-10-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0074_get_more_with_us_image_3_get_more_with_us_image_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(help_text='Admin sayfasında sizin göreceğiniz isim', max_length=200, verbose_name='Experience Adı'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='image',
            field=models.ForeignKey(db_constraint=False, help_text='313x580 boyutunda resim önerilmektedir.', on_delete=django.db.models.deletion.PROTECT, related_name='image1', to='appearance.image_for_information', verbose_name='Resim 1'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='image_2',
            field=models.ForeignKey(db_constraint=False, help_text='313x580 boyutunda resim önerilmektedir.', on_delete=django.db.models.deletion.PROTECT, related_name='image2', to='appearance.image_for_information', verbose_name='Resim 2'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='image_3',
            field=models.ForeignKey(db_constraint=False, help_text='313x580 boyutunda resim önerilmektedir.', on_delete=django.db.models.deletion.PROTECT, related_name='image3', to='appearance.image_for_information', verbose_name='Resim 3'),
        ),
        migrations.AlterField(
            model_name='get_more_with_us',
            name='image_4',
            field=models.ForeignKey(db_constraint=False, help_text='313x580 boyutunda resim önerilmektedir.', on_delete=django.db.models.deletion.PROTECT, related_name='image4', to='appearance.image_for_information', verbose_name='Resim 4'),
        ),
    ]
