# Generated by Django 4.1 on 2022-10-07 17:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0075_alter_experience_name_alter_get_more_with_us_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Adınız')),
                ('last_name', models.CharField(max_length=200, verbose_name='Soyadınız')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adresi')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True, verbose_name='Telefon numarası')),
                ('Company', models.CharField(blank=True, max_length=300, null=True, verbose_name='Şirket')),
                ('emailorphone', models.CharField(choices=[('Phone', 'Telefon'), ('Email', 'Mail')], max_length=100, verbose_name='İletişim Yolu')),
                ('message', models.CharField(max_length=5000, verbose_name='Mesajınız')),
            ],
        ),
    ]
