# Generated by Django 4.1 on 2022-10-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0076_contacform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacform',
            new_name='contactform',
        ),
    ]
