# Generated by Django 4.1 on 2022-10-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0077_rename_contacform_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200, verbose_name='Menü Adı')),
                ('menu_url', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Menü Url')),
                ('menu_status', models.CharField(choices=[('Published', 'Yayınla'), ('Draft', 'Taslak')], max_length=100, verbose_name='Menü Statüsü')),
            ],
        ),
    ]
