# Generated by Django 4.1 on 2022-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0078_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Sıra'),
        ),
    ]
