# Generated by Django 4.1 on 2022-10-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0079_footer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ('order',), 'verbose_name': 'footer', 'verbose_name_plural': 'footer'},
        ),
    ]
