# Generated by Django 4.1 on 2022-10-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0080_alter_footer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='menu_url',
            field=models.SlugField(max_length=300, unique=True, verbose_name='Menü Url'),
        ),
    ]
