# Generated by Django 4.1 on 2022-10-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0081_alter_footer_menu_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='emailorphone',
            field=models.CharField(choices=[('Phone', 'Telefon'), ('Email', 'Mail'), ('Both', 'İkiside Olabilir')], max_length=100, verbose_name='İletişim Yolu'),
        ),
    ]
