# Generated by Django 4.1 on 2022-10-08 20:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0082_alter_contactform_emailorphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='emailorphone',
            field=ckeditor.fields.RichTextField(choices=[('Phone', 'Telefon'), ('Email', 'Mail'), ('Both', 'İkiside Olabilir')], max_length=100, verbose_name='İletişim Yolu'),
        ),
    ]
