# Generated by Django 4.1 on 2022-10-08 21:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0083_alter_contactform_emailorphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='emailorphone',
            field=models.CharField(choices=[('Phone', 'Telefon'), ('Email', 'Mail'), ('Both', 'İkiside Olabilir')], max_length=100, verbose_name='İletişim Yolu'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Mesajınız'),
        ),
    ]
