# Generated by Django 4.1 on 2022-10-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0084_alter_contactform_emailorphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.CharField(max_length=5000, verbose_name='Mesajınız'),
        ),
    ]
