# Generated by Django 4.1 on 2022-10-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0085_alter_contactform_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='menu_kare',
            field=models.BooleanField(default=False, verbose_name='Menü kare Koyma Adı'),
        ),
    ]
