# Generated by Django 4.1 on 2022-10-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0086_footer_menu_kare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('banner_order',), 'verbose_name': 'Banner', 'verbose_name_plural': '5) Banner'},
        ),
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('order',), 'verbose_name': 'Experience', 'verbose_name_plural': '7) Experience'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('feature_order',), 'verbose_name': 'Feature', 'verbose_name_plural': '4) Feature'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ('order',), 'verbose_name': 'footer', 'verbose_name_plural': 'Footer'},
        ),
        migrations.AlterModelOptions(
            name='get_more_with_us',
            options={'ordering': ('order',), 'verbose_name': 'Bilgi', 'verbose_name_plural': '8) Bilgi'},
        ),
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'İcon', 'verbose_name_plural': '3) İcon'},
        ),
        migrations.AlterModelOptions(
            name='image_for_information',
            options={'verbose_name': 'Resim', 'verbose_name_plural': '9) Resim'},
        ),
        migrations.AlterModelOptions(
            name='information_gallery',
            options={'ordering': ('order',), 'verbose_name': 'Galeri Bilgisi', 'verbose_name_plural': '6) Galeri Bilgisi'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menü', 'verbose_name_plural': '1) Menü'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('slider_order',), 'verbose_name': 'Slider', 'verbose_name_plural': '2) Slider'},
        ),
    ]
